version: "3.9"

services:
  python-enviroment:
    build: .
    container_name: python-enviroment-container
    volumes:
      - .:/app
    tty: true
#    ports: 
#      - "8001:8001"    # cases/sms-pumping